events/urls.py
from django.urls import path
from events import views

app_name = 'events'

urlpatterns = [
    # /events/study/
    #path('study/', views.StudyView.as_view(), name='study'),
    # /events/study/apply/
    #path('study/apply/', views.StudyApplyView.as_view(), name='study_apply'),
    # /events/study/thanks/
    #path('study/thanks/', views.StudyThanksView.as_view(), name='study_thanks'),
]

havister/urls.py
from django.urls import path
from havister import views

app_name = 'havister'

urlpatterns = [
    # /havister/
    #path('', views.IndexView.as_view(), name='index'),
    # /havister/v1/market/
    path('v1/market/', views.market, name='market'),
    # /havister/v1/account/
    path('v1/account/', views.account, name='account'),
    # /havister/v1/signals/
    path('v1/signals/', views.signals, name='signals'),
    # /havister/v1/message/
    path('v1/message/', views.message, name='message'),
    # /havister/v1/trade/open/
    path('v1/trade/open/', views.trade_open, name='trade_open'),
    # /havister/v1/trade/close/
    path('v1/trade/close/', views.trade_close, name='trade_close'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    # /users/
    path('', views.IndexView.as_view(), name='index'),
    # /users/strategy/
    path('strategy/', views.StrategyView.as_view(), name='strategy'),
    # /users/strategy/add/
    path('strategy/add/', views.StrategyAddView.as_view(), name='strategy_add'),
    # /users/strategy/add/done/
    path('strategy/add/done/', views.StrategyAddDoneView.as_view(), name='strategy_add_done'),
    # /users/signal/
    path('signal/', views.SignalView.as_view(), name='signal'),
    # /users/signal/<pk>/
    path('signal/<int:pk>/', views.SignalDetailView.as_view(), name='signal_detail'),
    # /users/signal/add/
    path('signal/add/', views.SignalAddView.as_view(), name='signal_add'),
    # /users/signal/add/done/
    path('signal/add/done/', views.SignalAddDoneView.as_view(), name='signal_add_done'),
    # /users/havister/
    path('havister/', views.HavisterView.as_view(), name='havister'),
    # /users/trades/closed/
    path('trades/closed/', views.ClosedView.as_view(), name='trades_closed'),
    # /users/trades/opened/
    path('trades/opened/', views.OpenedView.as_view(), name='trades_opened'),
]

events/models.py
from django.db import models
from django.utils import timezone
from pointnut.commons import ChoiceInfo


class Launch(models.Model):
    name = models.CharField(max_length=30)
    gender_choice = models.CharField(max_length=1, choices=ChoiceInfo.GENDER_CHOICES)    
    age = models.PositiveSmallIntegerField()
    phone = models.CharField(max_length=11)
    is_married = models.BooleanField(default=False)
    job = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    has_fund = models.BooleanField(default=False)
    has_stock = models.BooleanField(default=False)
    has_derivative = models.BooleanField(default=False)
    recommender = models.CharField(max_length=30)
    date_submitted = models.DateTimeField(default=timezone.now)
    date_been_tester = models.DateField(null=True, blank=True)
    date_been_observer = models.DateField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "launches"

    def __str__(self):
        return self.name

    @property
    def masked_name(self):
        return f'{self.name[:2]}*'

    @property
    def gender(self):
        return ChoiceInfo.GENDERS[self.gender_choice]

    @property
    def masked_phone(self):
        part_one = self.phone[:3]
        part_three = self.phone[-4:]
        return f'{part_one}-****-{part_three}'


class Study(models.Model):
    name = models.CharField(max_length=30)
    gender_choice = models.CharField(max_length=1, choices=ChoiceInfo.GENDER_CHOICES)    
    age = models.PositiveSmallIntegerField()
    phone = models.CharField(max_length=11)
    is_married = models.BooleanField(default=False)
    job = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    has_fund = models.BooleanField(default=False)
    has_stock = models.BooleanField(default=False)
    has_derivative = models.BooleanField(default=False)
    recommender = models.CharField(max_length=30)
    date_submitted = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = "studies"

    def __str__(self):
        return f"{self.name} | {self.recommender} | {self.date_submitted.strftime('%Y-%m-%d %H:%M:%S')}"

    @property
    def gender(self):
        return ChoiceInfo.GENDERS[self.gender_choice]

havister/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    player = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages')
    degree = models.CharField(max_length=20, null=True, blank=True)
    text = models.CharField(max_length=200)
    datetime = models.DateTimeField()

    def __str__(self):
        return f'{self.player} | {self.degree} | {self.text} | {self.datetime}'

    @property
    def time_str(self):
        time = self.datetime.strftime('%H:%M:%S')
        return f'{time} | {self.text}'

events/forms.py
from django import forms


class LaunchForm(forms.Form):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = [
        (MALE, '남성'),
        (FEMALE, '여성')
    ]
    name = forms.CharField(label='name', max_length=30, min_length=2)
    gender_choice = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect(attrs={'class': 'form-check-input'}))
    age = forms.IntegerField(min_value=20, max_value=99)
    phone = forms.RegexField(label='phone', max_length=11, regex=r'^\d{3}\d{3,4}\d{4}$')
    is_married = forms.BooleanField(required=False)
    job = forms.CharField(label='job', max_length=30)
    city = forms.CharField(label='city', max_length=30)
    has_fund = forms.BooleanField(required=False)
    has_stock = forms.BooleanField(required=False)
    has_derivative = forms.BooleanField(required=False)
    recommender = forms.CharField(label='recommender', max_length=30, required=False)


class StudyForm(forms.Form):
    MALE = 'M'
    FEMALE = 'F'
    GENDER_CHOICES = [
        (MALE, '남성'),
        (FEMALE, '여성')
    ]
    name = forms.CharField(label='name', max_length=30, min_length=2)
    gender_choice = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect(attrs={'class': 'form-check-input'}))
    age = forms.IntegerField(min_value=20, max_value=99)
    phone = forms.RegexField(label='phone', max_length=11, regex=r'^\d{3}\d{3,4}\d{4}$')
    is_married = forms.BooleanField(required=False)
    job = forms.CharField(label='job', max_length=30)
    city = forms.CharField(label='city', max_length=30)
    has_fund = forms.BooleanField(required=False)
    has_stock = forms.BooleanField(required=False)
    has_derivative = forms.BooleanField(required=False)
    recommender = forms.CharField(label='recommender', max_length=30, required=False)

events/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from events.forms import LaunchForm, StudyForm
from events.models import Launch, Study


class IndexView(TemplateView):
    template_name = 'events/index.html'


class LaunchView(TemplateView):
    template_name = 'events/launch.html'


class LaunchApplyView(FormView):
    form_class = LaunchForm
    template_name = 'events/launch_apply.html'
    success_url = reverse_lazy('events:launch_thanks')

    def form_valid(self, form):
        # Cleaned Data
        name = form.cleaned_data['name']
        gender_choice = form.cleaned_data['gender_choice']
        age = form.cleaned_data['age']
        phone = form.cleaned_data['phone']
        is_married = form.cleaned_data['is_married']
        job = form.cleaned_data['job']
        city = form.cleaned_data['city']
        has_fund = form.cleaned_data['has_fund']
        has_stock = form.cleaned_data['has_stock']
        has_derivative = form.cleaned_data['has_derivative']
        recommender = form.cleaned_data['recommender']
        # Launch Create
        Launch.objects.create(
            name=name, gender_choice=gender_choice, age=age, phone=phone, is_married=is_married, job=job, city=city, 
            has_fund=has_fund, has_stock=has_stock, has_derivative=has_derivative, recommender=recommender,
        )
        return super().form_valid(form)


class LaunchThanksView(TemplateView):
    template_name = 'events/launch_thanks.html'


class LaunchNoticeView(TemplateView):
    template_name = 'events/launch_notice.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Tester list
        context['tester_list'] = Launch.objects.filter(
            date_been_tester__year=2019,
            date_been_tester__month=11
        ).order_by('name')
        return context


class StudyView(TemplateView):
    template_name = 'events/study.html'


class StudyApplyView(FormView):
    form_class = StudyForm
    template_name = 'events/study_apply.html'
    success_url = reverse_lazy('events:study_thanks')

    def form_valid(self, form):
        # Cleaned Data
        name = form.cleaned_data['name']
        gender_choice = form.cleaned_data['gender_choice']
        age = form.cleaned_data['age']
        phone = form.cleaned_data['phone']
        is_married = form.cleaned_data['is_married']
        job = form.cleaned_data['job']
        city = form.cleaned_data['city']
        has_fund = form.cleaned_data['has_fund']
        has_stock = form.cleaned_data['has_stock']
        has_derivative = form.cleaned_data['has_derivative']
        recommender = form.cleaned_data['recommender']
        # Study Create
        Study.objects.create(
            name=name, gender_choice=gender_choice, age=age, phone=phone, is_married=is_married, job=job, city=city, 
            has_fund=has_fund, has_stock=has_stock, has_derivative=has_derivative, recommender=recommender,
        )
        return super().form_valid(form)


class StudyThanksView(TemplateView):
    template_name = 'events/study_thanks.html'

havister/views.py
from django.utils import timezone
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from pointnut.commons import ChoiceInfo
from havister.models import Message
from markets.models import Market
from strategies.models import Signal
from players.models import Play, Trade
from decimal import Decimal, ROUND_HALF_UP
import json


class IndexView(TemplateView):
    template_name = 'havister/index.html'


def market(request):
    # Today
    date = timezone.now().date()
    today = Market.objects.filter(date=date, is_active=True).first()
    if today is None:
        start_time = "09:05:00"
        end_time = "15:15:00"
        # 5-Saturday, 6-Sunday
        is_holiday = True if date.weekday() >= 5 else False
    else:
        start_time = today.start_time
        end_time = today.end_time
        is_holiday = today.is_holiday
    # Today data
    data = {
        'Date': date,
        'StartTime': start_time,
        'EndTime': end_time,
        'IsHoliday': is_holiday
    }
    return JsonResponse(data, safe=False)


@csrf_exempt
def account(request):
    data = {}
    if request.method == 'POST':
        # JSON
        json_data = json.loads(request.body.decode('utf-8'))
        player = User.objects.filter(username=json_data['Player']).first()
        account = player.account
        # Account data
        data = account.as_json_dict
    return JsonResponse(data, safe=False)


@csrf_exempt
def signals(request):
    data = []
    if request.method == 'POST':
        # JSON
        json_data = json.loads(request.body.decode('utf-8'))
        player = User.objects.filter(username=json_data['Player']).first()
        plays = player.plays.filter(date_unbound__isnull=True).order_by('date_bound')

        for play in plays:
            # Signal
            signal = play.signal
            if signal.is_index is False:
                continue
            signal_data = signal.as_json_dict

            # Watch list
            today = timezone.now().date()
            watches = signal.watches.filter(
                date_started__lte=today,
                date_touched__isnull=True,
                is_active=True
            ).order_by('date_updated')

            # Signal <- Watch list
            signal_data['Watches'] = []
            for watch in watches:
                watch_data = watch.as_json_dict
                signal_data['Watches'].append(watch_data)
                
                # Order list
                close_orders = watch.orders.filter(status_choice='C', is_active=True). \
                    order_by('position_choice')
                open_orders = watch.orders.filter(status_choice='O', is_active=True). \
                    order_by('position_choice')

                # Watch <- Close order list
                watch_data['CloseOrders'] = []
                for order in close_orders:
                    trade = Trade.objects.filter(
                        player=player,
                        signal=order.watch.signal,
                        level=order.level,
                        position_choice=order.position_choice,
                        piece=order.piece,
                        date_closed__isnull=True
                    ).order_by('-date_opened').first()
                    if trade:
                        close_data = order.as_json_dict
                        close_data['Quantity'] = trade.quantity
                        watch_data['CloseOrders'].append(close_data)
                # Watch <- Open order list
                watch_data['OpenOrders'] = []
                for order in open_orders:
                    trade = Trade.objects.filter(
                        player=player,
                        signal=order.watch.signal,
                        level=order.level,
                        position_choice=order.position_choice,
                        piece=order.piece,
                        date_closed__isnull=True
                    ).order_by('-date_opened').first()
                    if not trade:
                        open_data = order.as_json_dict
                        watch_data['OpenOrders'].append(open_data)
            # Signal data
            data.append(signal_data)
    return JsonResponse(data, safe=False)


@csrf_exempt
def message(request):
    if request.method == 'POST':
        # JSON
        json_data = json.loads(request.body.decode('utf-8'))
        player = User.objects.filter(username=json_data['Player']).first()
        degree = json_data['Degree']
        text = json_data['Text']
        datetime = json_data['Datetime']
        # Message Create
        Message.objects.create(
            player=player, degree=degree, text=text, datetime=datetime
        )
    return HttpResponse('OK')


@csrf_exempt
def trade_open(request):
    if request.method == 'POST':
        # JSON
        json_data = json.loads(request.body.decode('utf-8'))
        player = User.objects.filter(username=json_data['Player']).first()
        signal = Signal.objects.filter(pk=json_data['SignalPk']).first()
        
        # Trade create
        Trade.objects.create(
            player=player, signal=signal,
            level=json_data['Level'], position_choice=json_data['PositionChoice'], piece=json_data['Piece'],
            quantity=json_data['Quantity'], price_opened=json_data['PriceOpened'], date_opened=json_data['DateOpened']
        )
    return HttpResponse('OK')


@csrf_exempt
def trade_close(request):
    if request.method == 'POST':
        # JSON
        json_data = json.loads(request.body.decode('utf-8'))
        player = User.objects.filter(username=json_data['Player']).first()
        signal = Signal.objects.filter(pk=json_data['SignalPk']).first()
        
        # Trade
        trade = Trade.objects.filter(
            player=player,
            signal=signal,
            level=json_data['Level'],
            position_choice=json_data['PositionChoice'],
            piece=json_data['Piece'],
            date_closed__isnull=True
        ).order_by('-date_opened').first()
        
        # Price
        price_opened = trade.price_opened
        price_closed = Decimal(json_data['PriceClosed'])
        difference = price_closed - price_opened
        change = (difference / price_opened * 100).quantize(Decimal('.01'), rounding=ROUND_HALF_UP)

        # Trade update
        trade.price_closed = price_closed
        trade.difference = difference
        trade.change = change
        trade.date_closed = json_data['DateClosed']
        trade.save()
    return HttpResponse('OK')

events/templates/events/havister.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Players - Pointnut</title>
{% endblock %}

{% block nav-title %}
<a class="mr-2" href="/"><i class="fas fa-chevron-left"></i></a>
<span>Events</span>
{% endblock %}

{% block nav-link %}
{% endblock %}

{% block header %}
<!-- Header -->
<header class="box">
  <div class="jumbotron text-center">
    <h1>로봇 #하비스터 출시 이벤트</h1>
    <h4 class="mb-3 text-pink">재테크, 이제 로봇으로 하자!</h4>
    <p class="lead">로봇으로 모의 계좌를 운영해 보세요. 수익이 나면 현금을 지급합니다.</p>
    <span class="text-muted">2019년 10월 ~ 12월</span>
  </div>
</header>
{% endblock %}

{% block main %}
<!-- Section -->
<section class="box-pad">
  <ul class="list-group">
    <li class="list-group-item">
      <div class="d-flex justify-content-between my-2">
        <h3>이벤트 신청</h3>
        <p class="h5"><span class="badge badge-green badge-pill">STEP 1</span></p>
      </div>
      <p><span class="text-pink">신청 양식</span>을 작성해 주세요.
        신청 양식은 이벤트 참여자를 추첨하고 발표하기 위해 사용됩니다.
        양식이 작성되면 신청이 완료됩니다.
      </p>
    </li>
    <li class="list-group-item">
      <div class="d-flex justify-content-between my-2">
        <h3>참여자 발표</h3>
        <p class="h5"><span class="badge badge-green badge-pill">STEP 2</span></p>
      </div>
      <p><span class="text-pink">매월 10명</span>을 추첨하여 발표합니다.
        이벤트 추첨은 당사의 내부 규정에 따라 진행되며, <span class="text-pink">매월 20일</span> 참여자를 발표합니다.
        개별 연락이 진행되며, 웹사이트에서 확인할 수 있습니다.
      </p>
    </li>
    <li class="list-group-item">
      <div class="d-flex justify-content-between my-2">
        <h3>모의계좌 개설</h3>
        <p class="h5"><span class="badge badge-green badge-pill">STEP 3</span></p>
      </div>
      <p><span class="text-pink">증권사</span>의 모의 계좌를 개설합니다.
        모의 계좌를 이용하면 <span class="text-pink">가상의 투자금</span>으로 위험없이 하비스터를 경험할 수 있습니다.
        이벤트에서는 (주)이베스트증권의 계좌를 사용합니다.
      </p>
    </li>
    <li class="list-group-item">
      <div class="d-flex justify-content-between my-2">
        <h3>하비스터 운영</h3>
        <p class="h5"><span class="badge badge-green badge-pill">STEP 4</span></p>
      </div>
      <p>하비스터는 자동화된 금융 트레이딩 <span class="text-pink">로봇</span>입니다.
        아마존 클라우드 서버에 설치되어, 국내 금융시장에 365일 자동으로 참여합니다.
        설치와 운영에 필요한 <span class="text-pink">교육</span>을 위해 본사 내방이 필요합니다.
      </p>
    </li>
    <li class="list-group-item">
      <div class="d-flex justify-content-between my-2">
        <h3>후기 올리기</h3>
        <p class="h5"><span class="badge badge-green badge-pill">STEP 5</span></p>
      </div>
      <p>하비스터를 운영하면 <span class="text-pink">수익</span>이 발생합니다.
        수익이 발생하면 <span class="text-pink">블로그</span>나 <span class="text-pink">SNS</span>에 로봇 사용 후기를 올려야 합니다.
        참여자 모두 수익도 얻고 재미있는 후기도 남기시기 바랍니다.
      </p>
    </li>
    <li class="list-group-item">
      <div class="d-flex justify-content-between my-2">
        <h3>수익금 받기</h3>
        <p class="h5"><span class="badge badge-green badge-pill">STEP 6</span></p>
      </div>
      <p><span class="text-pink">1인</span> 당
        <span class="text-pink">최대 100만원</span>의 수익금을 받을 수 있습니다.
        관련 법에 따라 이벤트 수익금이 5만원을 초과할 경우,
        제세 공과금(22%)를 제외 한 금액을 일시 또는 분할하여 지급합니다.
      </p>
    </li>
  </ul>
</section>

<!-- Section -->
<section class="box">
  <div class="jumbotron bg-cyan text-center text-white">
    <h1>"인스타 리그램"</h1>
    <p class="lead text-yellow">리그램 이벤트 참여만 해도 추첨 후 기프트콘 증정!!</p>
    <p class="mb-0">포인트넛의 이벤트 페이지를 필수 해시태그와 함께 인스타그램에 리그램 후 댓글 남기자~~</p>
    <p class="text-yellow">
      <span class="mr-2">#포인트넛</span>
      <span class="mr-2">#하비스터</span>
      <span class="mr-2">#로봇하비스터</span>
      <span>#로봇재테크</span>
    </p>
    <p>베스킨라빈스 파인트 기프트콘 100명 (추첨 증정)</p>
    <a class="btn btn-yellow px-4" href="" role="button">포인트넛 인스타그램</a>
  </div>
</section>
{% endblock %}

events/templates/events/notice.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Events - POINTNUT | 포인트넛</title>
{% endblock %}

{% block nav-title %}
<a class="mr-2 green" href="{% url 'events:index' %}"><i class="fas fa-chevron-left"></i></a>
<span>Events</span>
{% endblock %}

{% block nav-link %}
{% endblock %}

{% block header %}
<!-- Header -->
<header class="box">
  <div class="box-pad">
    <h1>런칭 이벤트</h1>
    <p class="mb-0">2019년 11월 이벤트 참여자를 발표합니다.</p>
  </div>
</header>
{% endblock %}

{% block main %}
<!-- Section -->
<section class="box text-kr">
  <div class="box-pad d-flex align-items-center">
    <h2 class="my-1">참여자</h2>
  </div>
  <!-- Section Body -->
  {% if tester_list %}
  <div class="box">
    {% for tester in tester_list %}
    <div class="box-pad d-flex align-items-center border-top">
      <div class="d-none d-sm-block w-25 text-center pr-3">
        <p class="h3 mb-0 font-weight-normal text-darkgray">{{ forloop.counter }}</p>
      </div>
      <div class="box flex-grow-1">
        <div class="d-flex align-items-center">
          <h5 class="mb-0 mr-auto">{{ tester.masked_name }}</h5>
          <p class="mb-0 h5">
            <span>{{ tester.masked_phone }}</span>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="box-pad">
    <p>아직 참여자가 선정되지 않았습니다.</p>
  </div>
  {% endif %}
</section>
{% endblock %}

events/templates/events/thanks.html
{% extends "base.html" %}
{% load static %}

{% block title %}
<title>Events - POINTNUT | 포인트넛</title>
{% endblock %}

{% block nav-title %}
<a class="mr-2 green" href="{% url 'events:index' %}"><i class="fas fa-chevron-left"></i></a>
<span>Events</span>
{% endblock %}

{% block nav-link %}
{% endblock %}

{% block header %}
<!-- Header -->
<header class="box">
  <div class="box-pad">
    <h1 class="mb-0">런칭 이벤트</h1>
  </div>
</header>
{% endblock %}

{% block main %}
<!-- Section -->
<section class="box-pad">
  <div class="my-2">
    <h2>Thanks!</h2>
    <p>이벤트 신청이 완료되었습니다.</p>
    <a class="btn btn-success px-4" href="{% url 'events:index' %}" role="button">확인</a>
  </div>
</section>
{% endblock %}