havister/urls.py
from django.urls import path
from havister import views

app_name = 'havister'

urlpatterns = [
    # /havister/
    #path('', views.IndexView.as_view(), name='index'),
    # /havister/v1/market/
    path('v1/market/', views.market, name='market'),
    # /havister/v1/account/
    path('v1/account/', views.account, name='account'),
    # /havister/v1/signals/
    path('v1/signals/', views.signals, name='signals'),
    # /havister/v1/message/
    path('v1/message/', views.message, name='message'),
    # /havister/v1/trade/open/
    path('v1/trade/open/', views.trade_open, name='trade_open'),
    # /havister/v1/trade/close/
    path('v1/trade/close/', views.trade_close, name='trade_close'),
]

signals/urls.py
from django.urls import path
from signals.views import IndexView

app_name = 'signals'

urlpatterns = [
    # /signals/
    path('', IndexView.as_view(), name='index'),
]

strategies/urls.py
from django.urls import path
from strategies.views import IndexView

app_name = 'strategies'

urlpatterns = [
    # /strategies/
    path('', IndexView.as_view(), name='index'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    # /users/
    path('', views.IndexView.as_view(), name='index'),
    # /users/strategy/
    path('strategy/', views.StrategyView.as_view(), name='strategy'),
    # /users/strategy/add/
    path('strategy/add/', views.StrategyAddView.as_view(), name='strategy_add'),
    # /users/strategy/add/done/
    path('strategy/add/done/', views.StrategyAddDoneView.as_view(), name='strategy_add_done'),
    # /users/signal/
    path('signal/', views.SignalView.as_view(), name='signal'),
    # /users/signal/<pk>/
    path('signal/<int:pk>/', views.SignalDetailView.as_view(), name='signal_detail'),
    # /users/signal/add/
    path('signal/add/', views.SignalAddView.as_view(), name='signal_add'),
    # /users/signal/add/done/
    path('signal/add/done/', views.SignalAddDoneView.as_view(), name='signal_add_done'),
    # /users/havister/
    path('havister/', views.HavisterView.as_view(), name='havister'),
    # /users/trades/closed/
    path('trades/closed/', views.ClosedView.as_view(), name='trades_closed'),
    # /users/trades/opened/
    path('trades/opened/', views.OpenedView.as_view(), name='trades_opened'),
]

havister/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    player = models.ForeignKey(User, on_delete=models.CASCADE, related_name='messages')
    degree = models.CharField(max_length=20, null=True, blank=True)
    text = models.CharField(max_length=200)
    datetime = models.DateTimeField()

    def __str__(self):
        return f'{self.player} | {self.degree} | {self.text} | {self.datetime}'

    @property
    def time_str(self):
        time = self.datetime.strftime('%H:%M:%S')
        return f'{time} | {self.text}'

users/models.py
from django.db import models

# Create your models here.

havister/views.py
from django.utils import timezone
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from pointnut.commons import ChoiceInfo
from havister.models import Message
from markets.models import Market
from strategies.models import Signal
from players.models import Play, Trade
from decimal import Decimal, ROUND_HALF_UP
import json


class IndexView(TemplateView):
    template_name = 'havister/index.html'


def market(request):
    # Today
    date = timezone.now().date()
    today = Market.objects.filter(date=date, is_active=True).first()
    if today is None:
        start_time = "09:05:00"
        end_time = "15:15:00"
        # 5-Saturday, 6-Sunday
        is_holiday = True if date.weekday() >= 5 else False
    else:
        start_time = today.start_time
        end_time = today.end_time
        is_holiday = today.is_holiday
    # Today data
    data = {
        'Date': date,
        'StartTime': start_time,
        'EndTime': end_time,
        'IsHoliday': is_holiday
    }
    return JsonResponse(data, safe=False)


@csrf_exempt
def account(request):
    data = {}
    if request.method == 'POST':
        # JSON
        json_data = json.loads(request.body.decode('utf-8'))
        player = User.objects.filter(username=json_data['Player']).first()
        account = player.account
        # Account data
        data = account.as_json_dict
    return JsonResponse(data, safe=False)


@csrf_exempt
def signals(request):
    data = []
    if request.method == 'POST':
        # JSON
        json_data = json.loads(request.body.decode('utf-8'))
        player = User.objects.filter(username=json_data['Player']).first()
        plays = player.plays.filter(date_unbound__isnull=True).order_by('date_bound')

        for play in plays:
            # Signal
            signal = play.signal
            if signal.is_index is False:
                continue
            signal_data = signal.as_json_dict

            # Watch list
            today = timezone.now().date()
            watches = signal.watches.filter(
                date_started__lte=today,
                date_touched__isnull=True,
                is_active=True
            ).order_by('date_updated')

            # Signal <- Watch list
            signal_data['Watches'] = []
            for watch in watches:
                watch_data = watch.as_json_dict
                signal_data['Watches'].append(watch_data)
                
                # Order list
                close_orders = watch.orders.filter(status_choice='C', is_active=True). \
                    order_by('position_choice')
                open_orders = watch.orders.filter(status_choice='O', is_active=True). \
                    order_by('position_choice')

                # Watch <- Close order list
                watch_data['CloseOrders'] = []
                for order in close_orders:
                    trade = Trade.objects.filter(
                        player=player,
                        signal=order.watch.signal,
                        level=order.level,
                        position_choice=order.position_choice,
                        piece=order.piece,
                        date_closed__isnull=True
                    ).order_by('-date_opened').first()
                    if trade:
                        close_data = order.as_json_dict
                        close_data['Quantity'] = trade.quantity
                        watch_data['CloseOrders'].append(close_data)
                # Watch <- Open order list
                watch_data['OpenOrders'] = []
                for order in open_orders:
                    trade = Trade.objects.filter(
                        player=player,
                        signal=order.watch.signal,
                        level=order.level,
                        position_choice=order.position_choice,
                        piece=order.piece,
                        date_closed__isnull=True
                    ).order_by('-date_opened').first()
                    if not trade:
                        open_data = order.as_json_dict
                        watch_data['OpenOrders'].append(open_data)
            # Signal data
            data.append(signal_data)
    return JsonResponse(data, safe=False)


@csrf_exempt
def message(request):
    if request.method == 'POST':
        # JSON
        json_data = json.loads(request.body.decode('utf-8'))
        player = User.objects.filter(username=json_data['Player']).first()
        degree = json_data['Degree']
        text = json_data['Text']
        datetime = json_data['Datetime']
        # Message Create
        Message.objects.create(
            player=player, degree=degree, text=text, datetime=datetime
        )
    return HttpResponse('OK')


@csrf_exempt
def trade_open(request):
    if request.method == 'POST':
        # JSON
        json_data = json.loads(request.body.decode('utf-8'))
        player = User.objects.filter(username=json_data['Player']).first()
        signal = Signal.objects.filter(pk=json_data['SignalPk']).first()
        
        # Trade create
        Trade.objects.create(
            player=player, signal=signal,
            level=json_data['Level'], position_choice=json_data['PositionChoice'], piece=json_data['Piece'],
            quantity=json_data['Quantity'], price_opened=json_data['PriceOpened'], date_opened=json_data['DateOpened']
        )
    return HttpResponse('OK')


@csrf_exempt
def trade_close(request):
    if request.method == 'POST':
        # JSON
        json_data = json.loads(request.body.decode('utf-8'))
        player = User.objects.filter(username=json_data['Player']).first()
        signal = Signal.objects.filter(pk=json_data['SignalPk']).first()
        
        # Trade
        trade = Trade.objects.filter(
            player=player,
            signal=signal,
            level=json_data['Level'],
            position_choice=json_data['PositionChoice'],
            piece=json_data['Piece'],
            date_closed__isnull=True
        ).order_by('-date_opened').first()
        
        # Price
        price_opened = trade.price_opened
        price_closed = Decimal(json_data['PriceClosed'])
        difference = price_closed - price_opened
        change = (difference / price_opened * 100).quantize(Decimal('.01'), rounding=ROUND_HALF_UP)

        # Trade update
        trade.price_closed = price_closed
        trade.difference = difference
        trade.change = change
        trade.date_closed = json_data['DateClosed']
        trade.save()
    return HttpResponse('OK')

signals/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'signals/index.html'

strategies/views.py
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'strategies/index.html'

users/views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView, View
from django.db.models import Subquery, Sum
from markets.models import Market
from strategies.models import Strategy, Signal
from players.models import Shopping, Play
import datetime


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'users/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Group
        group = user.groups.filter(name__in=['player', 'observer']).first()
        context['group'] = group
        # Closed trade list
        context['closed_trade_list'] = user.trades.filter(date_closed__isnull=False). \
            order_by('-date_closed')[:3]
        # Opened trade list
        context['opened_trade_list'] = user.trades.filter(date_closed__isnull=True). \
            order_by('-date_opened')[:3]
        return context


class StrategyView(LoginRequiredMixin, TemplateView):
    template_name = 'users/strategy.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Shopping list
        context['shopping_list'] = user.shoppings.filter(date_unbound__isnull=True). \
            order_by('-date_bound')
        return context


class StrategyAddView(LoginRequiredMixin, TemplateView):
    template_name = 'users/strategy_add.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        shoppings = user.shoppings.filter(date_unbound__isnull=True)
        # Strategy list
        context['strategy_list'] = Strategy.objects.filter(is_active=True). \
            exclude(pk__in=Subquery(shoppings.values('strategy'))). \
            order_by('name')
        return context


class StrategyAddDoneView(LoginRequiredMixin, View):
    def post(self, request,*args, **kwargs):
        user = request.user
        strategy_id = request.POST['strategy_id']
        strategy = Strategy.objects.filter(id=strategy_id).first()
        # Strategy add
        if strategy:
            Shopping.objects.create(player=user, strategy=strategy)
        return redirect('users:strategy')


class SignalView(LoginRequiredMixin, TemplateView):
    template_name = 'users/signal.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Play list
        context['play_list'] = user.plays.filter(date_unbound__isnull=True). \
            order_by('-date_bound')
        return context


class SignalDetailView(LoginRequiredMixin, TemplateView):
    template_name = 'users/signal_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Signal
        signal = get_object_or_404(Signal, pk=context['pk'])
        context['signal'] = signal
        # Watch list
        watch_list = []
        watches = signal.watches.filter(date_touched__isnull=True, is_active=True). \
            order_by('-date_updated')
        for watch in watches:
            # Order list
            open_orders = watch.orders.filter(status_choice='O', is_active=True). \
                order_by('position_choice')
            close_orders = watch.orders.filter(status_choice='C', is_active=True). \
                order_by('position_choice')
            watch_list.append({'item': watch, 'open_orders': open_orders, 'close_orders': close_orders})
        context['watch_list'] = watch_list
        return context


class SignalAddView(LoginRequiredMixin, TemplateView):
    template_name = 'users/signal_add.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        plays = user.plays.filter(date_unbound__isnull=True)
        shoppings = user.shoppings.filter(date_unbound__isnull=True)
        # Budget
        context['budget'] = user.account.primary_budget
        context['budget_used'] = plays.aggregate(sum=Sum('signal__total_amount'))['sum'] or 0
        context['budget_unused'] = context['budget'] - context['budget_used']
        # Signal list
        context['signal_list'] = Signal.objects. \
            filter(strategy__in=Subquery(shoppings.values('strategy')), is_active=True). \
            exclude(pk__in=Subquery(plays.values('signal'))). \
            order_by('strategy')
        return context


class SignalAddDoneView(LoginRequiredMixin, View):
    def post(self, request,*args, **kwargs):
        user = request.user
        signal_id = request.POST['signal_id']
        signal = Signal.objects.filter(id=signal_id).first()
        # Signal add
        if signal:
            Play.objects.create(player=user, signal=signal)
        return redirect('users:signal')


class HavisterView(LoginRequiredMixin, TemplateView):
    template_name = 'users/havister.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Market time
        start_time = datetime.time(9, 0)
        end_time = datetime.time(15, 45)
        # Today
        now = timezone.now()
        today = now.date()
        time = now.time()
        messages = user.messages.filter(datetime__date=today).order_by('pk')
        market = Market.objects.filter(date=today, is_active=True).first()
        # Messages
        message_list = []
        if messages:
            for message in messages:
                message_list.append(message.time_str)
        else:
            if today.weekday() >= 5: # 5-Saturday, 6-Sunday
                message_list.append("오늘은 휴장일 입니다.")
            if market:
                if market.is_holiday:
                    message_list.append("오늘은 휴장일 입니다.")
            if len(message_list) == 0:
                message_list.append("하비스터가 준비 중 입니다.")
                if time >= start_time:
                    message_list.append(start_time.strftime('%H:%M:%S') + " | 하비스터가 시장을 감시 중 입니다.")
                if time > end_time:
                    message_list.append(end_time.strftime('%H:%M:%S') + " | 시장이 마감 되었습니다.")
                    message_list.append("하비스터가 종료 되었습니다.")
        context['message_list'] = message_list
        # Closed trade list
        context['closed_trade_list'] = user.trades.filter(date_closed__date=today). \
            order_by('-date_closed')
        # Opened trade list
        context['opened_trade_list'] = user.trades.filter(date_opened__date=today, date_closed__isnull=True). \
            order_by('-date_opened')
        return context


class ClosedView(LoginRequiredMixin, TemplateView):
    template_name = 'users/closed_trade_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Closed trade list
        context['trade_list'] = user.trades.filter(date_closed__isnull=False). \
            order_by('-date_closed')
        return context


class OpenedView(LoginRequiredMixin, TemplateView):
    template_name = 'users/opened_trade_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Opened trade list
        context['trade_list'] = user.trades.filter(date_closed__isnull=True). \
            order_by('-date_opened')
        return context

users/templates/users/havister.html
{% extends "user_base.html" %}
{% load humanize %}
{% load extras %}

{% block title %}
<title>하비스터 - 포인트넛</title>
{% endblock %}

{% block nav-title %}
<a class="mr-2 green" href="{% url 'users:index' %}"><i class="fas fa-chevron-left"></i></a>
<span>Havister</span>
{% endblock %}

{% block header %}
<!-- Header -->
<header class="box text-kr">
  <div class="box-pad d-flex justify-content-between align-items-center">
    <h1 class="my-1">하비스터</h1>
    <a class="btn btn-outline-secondary" href="{% url 'users:havister' %}" role="button"><i class='fas fa-redo'></i></a>
  </div>
  <div class="box-pad-x">
    <form class="pb-3">
      <div class="form-group mb-0 p-2 border">
        {% if user.account.has_havister %}
        <textarea class="havister" id="havister-status" rows="10">{% for message in message_list %}{{ message }}&#13;{% endfor %}</textarea>
        {% else %}
        <textarea class="havister" rows="10" disabled>하비스터 사용권 등록이 필요합니다.</textarea>
        {% endif %}
      </div>
    </form>
  </div>
</header>
{% endblock %}

{% block main %}
<!-- Section -->
<section class="box text-kr">
  <div class="box-pad d-flex align-items-center">
    <h2 class="my-1 text-darkgray mr-auto">오늘 청산 거래</h2>
    <div></div>
  </div>
  <!-- Section Body -->
  {% if closed_trade_list %}
  <div class="box">
    {% for trade in closed_trade_list %}
    <div class="box-pad d-flex align-items-center border-top">
      <div class="d-none d-sm-block w-25 text-center pr-3">
        <p class="h3 font-weight-normal text-darkgray">{{ forloop.counter }}</p>
      </div>
      <div class="box flex-grow-1">
        <div class="d-flex align-items-center">
          <h5 class="mr-auto">{{ trade.signal.asset|upper }}</h5>
          <p class="h5 {{ trade.change|change_class }}">
            <span>{{ trade.change|stringformat:"+0.2f" }}%</span>
          </p>
        </div>
        <div class="d-flex">
          <p class="mb-0 small text-muted mr-auto">
            <span>{{ trade.date_opened|date:'Y.m.d' }}</span>
            <span>~</span>
            <span>{{ trade.date_closed|date:'Y.m.d' }}</span>
          </p>
          <p class="mb-0 small text-muted">
            <span>{{ trade.signal.strategy }}</span> /
            <span>{{ trade.position }}</span>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="box-pad">
    <span class="text-muted">거래 기록이 없습니다.</span>
  </div>
  {% endif %}
</section>

<!-- Section -->
<section class="box text-kr">
  <div class="box-pad d-flex align-items-center">
    <h2 class="my-1 text-darkgray mr-auto">오늘 진입 거래</h2>
    <div></div>
  </div>
  <!-- Section Body -->
  {% if opened_trade_list %}
  <div class="box">
    {% for trade in opened_trade_list %}
    <div class="box-pad d-flex align-items-center border-top">
      <div class="d-none d-sm-block w-25 text-center pr-3">
        <p class="h3 font-weight-normal text-darkgray">{{ forloop.counter }}</p>
      </div>
      <div class="box flex-grow-1">
        <div class="d-flex align-items-center">
          <h5 class="mr-auto">{{ trade.signal.asset|upper }}</h5>
          <p class="h5 text-muted">
            <span class="text-cyan"><i class="fas fa-plane-departure"></i></span>
          </p>
        </div>
        <div class="d-flex">
          <p class="mb-0 small text-muted mr-auto">
            <span>{{ trade.date_opened|date:'Y.m.d' }}</span>
            <span class="mr-3">~</span>
            <span><i class="far fa-hourglass"></i> Signal Waiting</span>
          </p>
          <p class="mb-0 small text-muted">
            <span>{{ trade.signal.strategy }}</span> /
            <span>{{ trade.position }}</span>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="box-pad">
    <span class="text-muted">거래 기록이 없습니다.</span>
  </div>
  {% endif %}
</section>

{% endblock %}

users/templates/users/index.html
{% extends "user_base.html" %}
{% load humanize %}
{% load extras %}

{% block title %}
<title>홈 - 포인트넛</title>
{% endblock %}

{% block nav-title %}
<a class="mr-2 green" href="/"><i class="fas fa-chevron-left"></i></a>
<span>{{ user.username|upper }}</span>
{% endblock %}

{% block header %}
<!-- Header -->
<header class="box text-kr">
  <div class="box-pad d-flex justify-content-between align-items-center">
    <h1 class="my-1">{{ user.first_name }}</h1>
    <p class="mb-0 h5 text-capitalize">
      <span class="badge badge-pill badge-orange font-weight-normal">{{ group.name }}</span>
    </p>
  </div>
  {% if user.account %}
  <div class="box-pad-x">
    <ul class="list-group pb-3">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <p class="h5 my-2">계좌 설정 일자</p>
        <p class="h5 my-2">{{ user.account.date_bound|date:'Y년 m월 d일' }}</p>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <p class="h5 my-2">계좌 활성 상태</p>
        <p class="h5 my-2">
          {% if user.account.is_active %}활성 <i class="fas fa-check-circle text-info"></i>
          {% else %}비활성 <i class="fas fa-minus-circle text-gray"></i>{% endif %}
        </p>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <p class="h5 my-2">주식계좌 설정 금액</p>
        <p class="h5 my-2">{{ user.account.primary_budget|intcomma }}원</p>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <p class="h5 my-2">파생계좌 설정 금액</p>
        <p class="h5 my-2">{{ user.account.secondary_budget|intcomma }}원</p>
      </li>
    </ul>
  </div>
  {% else %}
  <div class="box-pad">
    <span>계좌 정보가 없습니다.</span>
  </div>
  {% endif %}
</header>
{% endblock %}

{% block main %}
<!-- Section -->
<section class="box text-kr">
  <div class="box-pad d-flex justify-content-between align-items-center">
    <h2 class="my-1 text-darkgray">최근 청산</h2>
    <div class="mb-0 h4">
      <a class="green" href="{% url 'users:trades_closed' %}"><i class="fas fa-chevron-right"></i></a>
    </div>
  </div>
  <!-- Section Body -->
  {% if closed_trade_list %}
  <div class="box">
    {% for trade in closed_trade_list %}
    <div class="box-pad d-flex align-items-center border-top">
      <div class="d-none d-sm-block w-25 text-center pr-3">
        <p class="h3 font-weight-normal text-darkgray">{{ forloop.counter }}</p>
      </div>
      <div class="box flex-grow-1">
        <div class="d-flex align-items-center">
          <h5 class="mr-auto">{{ trade.signal.asset|upper }}</h5>
          <p class="h5 {{ trade.change|change_class }}">
            <span>{{ trade.change|stringformat:"+0.2f" }}%</span>
          </p>
        </div>
        <div class="d-flex">
          <p class="mb-0 small text-muted mr-auto">
            <span>{{ trade.date_opened|date:'Y.m.d' }}</span>
            <span>~</span>
            <span>{{ trade.date_closed|date:'Y.m.d' }}</span>
          </p>
          <p class="mb-0 small text-muted">
            <span>{{ trade.signal.strategy }}</span> /
            <span>{{ trade.position }}</span>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="box-pad">
    <span>거래 기록이 없습니다.</span>
  </div>
  {% endif %}
</section>

<!-- Section -->
<section class="box text-kr">
  <div class="box-pad d-flex justify-content-between align-items-center">
    <h2 class="my-1 text-darkgray">최근 진입</h2>
    <div class="mb-0 h4">
      <a class="green" href="{% url 'users:trades_opened' %}"><i class="fas fa-chevron-right"></i></a>
    </div>
  </div>
  <!-- Section Body -->
  {% if opened_trade_list %}
  <div class="box">
    {% for trade in opened_trade_list %}
    <div class="box-pad d-flex align-items-center border-top">
      <div class="d-none d-sm-block w-25 text-center pr-3">
        <p class="h3 font-weight-normal text-darkgray">{{ forloop.counter }}</p>
      </div>
      <div class="box flex-grow-1">
        <div class="d-flex align-items-center">
          <h5 class="mr-auto">{{ trade.signal.asset|upper }}</h5>
          <p class="h5 text-muted">
            <span class="text-cyan"><i class="fas fa-plane-departure"></i></span>
          </p>
        </div>
        <div class="d-flex">
          <p class="mb-0 small text-muted mr-auto">
            <span>{{ trade.date_opened|date:'Y.m.d' }}</span>
            <span class="mr-3">~</span>
            <span><i class="far fa-hourglass"></i> Signal Waiting</span>
          </p>
          <p class="mb-0 small text-muted">
            <span>{{ trade.signal.strategy }}</span> /
            <span>{{ trade.position }}</span>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="box-pad">
    <span>거래 기록이 없습니다.</span>
  </div>
  {% endif %}
</section>

{% endblock %}

users/templates/users/signal.html
{% extends "user_base.html" %}
{% load humanize %}
{% load extras %}

{% block title %}
<title>시그널 - 포인트넛</title>
{% endblock %}

{% block nav-title %}
<a class="mr-2 green" href="{% url 'users:index' %}"><i class="fas fa-chevron-left"></i></a>
<span>Signal</span>
{% endblock %}

{% block header %}
<!-- Header -->
<header class="box text-kr">
  <div class="box-pad d-flex justify-content-between align-items-center">
    <h1 class="my-1">시그널</h1>
    <a class="btn btn-success" href="{% url 'users:signal_add' %}" role="button">시그널 추가</a>
  </div>
</header>
{% endblock %}

{% block main %}
<!-- Section -->
{% if user.account.has_havister %}

{% if play_list %}
{% for play in play_list %}
<!-- Signal -->
<section class="box-pad text-kr">
  <div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h4 class="mb-0">{{ play.signal.strategy }}</h4>
      <a class="card-link h4 mb-0 green" href="{% url 'users:signal_detail' play.signal.pk %}"><i class="fas fa-chevron-right"></i></a>
    </div>
    <div class="card-body">
      <div class="card-text d-flex justify-content-between align-items-center">
        <h4 class="card-title mb-0 font-weight-bold">{{ play.signal.asset }}</h4>
        <p class="h5 mb-0 text-muted">{{ play.signal.total_amount|intcomma }}원</h4>
      </div>
      <hr>
      <p class="card-text d-flex justify-content-between">
        <span>Long</span>
        <strong>{{ play.signal.long_etf }}</strong>
      </p>
      <p class="card-text d-flex justify-content-between">
        <span>Short</span>
        <strong>{{ play.signal.short_etf|default_if_none:"없음" }}</strong>
      </p>
      <hr>
      <p class="card-text">
        <small class="text-muted">{{ play.date_bound|date:'Y-m-d' }} 추가</small>
      </p>
    </div>
  </div>
</section>
{% endfor %}
{% else %}
<section class="box text-kr">
  <div class="box-pad">
    <span>보유 시그널이 없습니다.</span>
  </div>
</section>
{% endif %}

{% else %}
<section class="box text-kr">
  <div class="box-pad">
    <span class="text-danger">하비스터 사용 권한이 필요합니다.</span>
  </div>
</section>
{% endif %}
{% endblock %}