players/urls.py
from django.urls import path
from players import views

app_name = 'players'

urlpatterns = [
    # /players/
    path('', views.IndexView.as_view(), name='index'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    # /users/
    path('', views.IndexView.as_view(), name='index'),
    # /users/strategy/
    path('strategy/', views.StrategyView.as_view(), name='strategy'),
    # /users/strategy/add/
    path('strategy/add/', views.StrategyAddView.as_view(), name='strategy_add'),
    # /users/strategy/add/done/
    path('strategy/add/done/', views.StrategyAddDoneView.as_view(), name='strategy_add_done'),
    # /users/signal/
    path('signal/', views.SignalView.as_view(), name='signal'),
    # /users/signal/<pk>/
    path('signal/<int:pk>/', views.SignalDetailView.as_view(), name='signal_detail'),
    # /users/signal/add/
    path('signal/add/', views.SignalAddView.as_view(), name='signal_add'),
    # /users/signal/add/done/
    path('signal/add/done/', views.SignalAddDoneView.as_view(), name='signal_add_done'),
    # /users/havister/
    path('havister/', views.HavisterView.as_view(), name='havister'),
    # /users/trades/closed/
    path('trades/closed/', views.ClosedView.as_view(), name='trades_closed'),
    # /users/trades/opened/
    path('trades/opened/', views.OpenedView.as_view(), name='trades_opened'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView, View
from django.db.models import Subquery, Sum
from markets.models import Market
from strategies.models import Strategy, Signal
from players.models import Shopping, Play
import datetime


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'users/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Group
        group = user.groups.filter(name__in=['player', 'observer']).first()
        context['group'] = group
        # Closed trade list
        context['closed_trade_list'] = user.trades.filter(date_closed__isnull=False). \
            order_by('-date_closed')[:3]
        # Opened trade list
        context['opened_trade_list'] = user.trades.filter(date_closed__isnull=True). \
            order_by('-date_opened')[:3]
        return context


class StrategyView(LoginRequiredMixin, TemplateView):
    template_name = 'users/strategy.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Shopping list
        context['shopping_list'] = user.shoppings.filter(date_unbound__isnull=True). \
            order_by('-date_bound')
        return context


class StrategyAddView(LoginRequiredMixin, TemplateView):
    template_name = 'users/strategy_add.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        shoppings = user.shoppings.filter(date_unbound__isnull=True)
        # Strategy list
        context['strategy_list'] = Strategy.objects.filter(is_active=True). \
            exclude(pk__in=Subquery(shoppings.values('strategy'))). \
            order_by('name')
        return context


class StrategyAddDoneView(LoginRequiredMixin, View):
    def post(self, request,*args, **kwargs):
        user = request.user
        strategy_id = request.POST['strategy_id']
        strategy = Strategy.objects.filter(id=strategy_id).first()
        # Strategy add
        if strategy:
            Shopping.objects.create(player=user, strategy=strategy)
        return redirect('users:strategy')


class SignalView(LoginRequiredMixin, TemplateView):
    template_name = 'users/signal.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Play list
        context['play_list'] = user.plays.filter(date_unbound__isnull=True). \
            order_by('-date_bound')
        return context


class SignalDetailView(LoginRequiredMixin, TemplateView):
    template_name = 'users/signal_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Signal
        signal = get_object_or_404(Signal, pk=context['pk'])
        context['signal'] = signal
        # Watch list
        watch_list = []
        watches = signal.watches.filter(date_touched__isnull=True, is_active=True). \
            order_by('-date_updated')
        for watch in watches:
            # Order list
            open_orders = watch.orders.filter(status_choice='O', is_active=True). \
                order_by('position_choice')
            close_orders = watch.orders.filter(status_choice='C', is_active=True). \
                order_by('position_choice')
            watch_list.append({'item': watch, 'open_orders': open_orders, 'close_orders': close_orders})
        context['watch_list'] = watch_list
        return context


class SignalAddView(LoginRequiredMixin, TemplateView):
    template_name = 'users/signal_add.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        plays = user.plays.filter(date_unbound__isnull=True)
        shoppings = user.shoppings.filter(date_unbound__isnull=True)
        # Budget
        context['budget'] = user.account.primary_budget
        context['budget_used'] = plays.aggregate(sum=Sum('signal__total_amount'))['sum'] or 0
        context['budget_unused'] = context['budget'] - context['budget_used']
        # Signal list
        context['signal_list'] = Signal.objects. \
            filter(strategy__in=Subquery(shoppings.values('strategy')), is_active=True). \
            exclude(pk__in=Subquery(plays.values('signal'))). \
            order_by('strategy')
        return context


class SignalAddDoneView(LoginRequiredMixin, View):
    def post(self, request,*args, **kwargs):
        user = request.user
        signal_id = request.POST['signal_id']
        signal = Signal.objects.filter(id=signal_id).first()
        # Signal add
        if signal:
            Play.objects.create(player=user, signal=signal)
        return redirect('users:signal')


class HavisterView(LoginRequiredMixin, TemplateView):
    template_name = 'users/havister.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Market time
        start_time = datetime.time(9, 0)
        end_time = datetime.time(15, 45)
        # Today
        now = timezone.now()
        today = now.date()
        time = now.time()
        messages = user.messages.filter(datetime__date=today).order_by('pk')
        market = Market.objects.filter(date=today, is_active=True).first()
        # Messages
        message_list = []
        if messages:
            for message in messages:
                message_list.append(message.time_str)
        else:
            if today.weekday() >= 5: # 5-Saturday, 6-Sunday
                message_list.append("오늘은 휴장일 입니다.")
            if market:
                if market.is_holiday:
                    message_list.append("오늘은 휴장일 입니다.")
            if len(message_list) == 0:
                message_list.append("하비스터가 준비 중 입니다.")
                if time >= start_time:
                    message_list.append(start_time.strftime('%H:%M:%S') + " | 하비스터가 시장을 감시 중 입니다.")
                if time > end_time:
                    message_list.append(end_time.strftime('%H:%M:%S') + " | 시장이 마감 되었습니다.")
                    message_list.append("하비스터가 종료 되었습니다.")
        context['message_list'] = message_list
        # Closed trade list
        context['closed_trade_list'] = user.trades.filter(date_closed__date=today). \
            order_by('-date_closed')
        # Opened trade list
        context['opened_trade_list'] = user.trades.filter(date_opened__date=today, date_closed__isnull=True). \
            order_by('-date_opened')
        return context


class ClosedView(LoginRequiredMixin, TemplateView):
    template_name = 'users/closed_trade_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Closed trade list
        context['trade_list'] = user.trades.filter(date_closed__isnull=False). \
            order_by('-date_closed')
        return context


class OpenedView(LoginRequiredMixin, TemplateView):
    template_name = 'users/opened_trade_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # Opened trade list
        context['trade_list'] = user.trades.filter(date_closed__isnull=True). \
            order_by('-date_opened')
        return context

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block meta %}{% endblock %}
  {% block title %}<title>포인트넛</title>{% endblock %}
  <link rel="icon" href="{% static 'favicon.ico' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<!-- Navigation -->
<nav class="box-pad">
  <div class="d-flex justify-content-between align-items-center">
    <div class="mb-0 h4">
    {% block nav-title %}{% endblock %}
    </div>
    <div class="mb-0 h6">
    {% block nav-link %}
      {% if user.is_active %}
      <a class="btn btn-outline-success btn-sm" href="{% url 'users:index' %}" role="button">{{ user.username|upper }}</a>
      {% else %}
      <a class="btn btn-outline-success btn-sm" href="{% url 'login' %}" role="button">Login</a>
      {% endif %}
    {% endblock %}
    </div>
  </div>
</nav>

<!-- Content -->
<main class="box">
{% block header %}{% endblock %}
{% block main %}{% endblock %}
</main>

<!-- Footer -->
<footer class="box-pad">
  <p class="mb-0 text-center text-muted">
    <small>Copyright © 2020 Pointnut Inc.</small>
  </p>
</footer>

<!-- JavaScript for Bootstrap -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!-- Custom Script -->
{% block script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block nav-title %}
<span>POINTNUT</span>
{% endblock %}

{% block nav-link %}
  {% if user.is_active %}
  <a class="btn btn-outline-primary btn-xm" href="{% url 'players:index' %}" role="button">Players</a>
  {% else %}
  <a class="btn btn-outline-primary btn-xm" href="{% url 'login' %}" role="button">Login</a>
  {% endif %}
{% endblock %}

{% block header %}
<!-- Header -->
<header class="box">
  <div class="jumbotron text-center">
    <h1>재테크, 이제 로봇으로 하자!</h1>
    <p class="lead">로봇으로 모의 계좌를 운영해 보세요. 수익이 나면 현금을 지급합니다.</p>
    <p>로봇 <strong>HAVISTER</strong> 출시 이벤트</p>
    <a class="btn btn-primary px-4" href="/events/havister/" role="button">이벤트 보기</a>
  </div>
</header>
{% endblock %}

{% block main %}
<!-- Section -->
<section class="box">
  <img class="box-img" src="{% static 'images/squirrel.jpg' %}" alt="Havister Logo">
  <div class="box-pad">
    <h4 class="my-3">하비스터(Havister)</h4>
    <p>하비스터는 금융 거래를 위한 자동화된 프로그램 매매 시스템입니다. 지금껏 금융사들의 전유물이었던 이 훌륭한 도구를 이제는 개인들도 사용할 수 있게 되었습니다.</p>
    <p>이 시스템은 로봇 소프트웨어(Havister), 이용자(Player), 매매 신호(Signal), 신호 개발자(Creator)가 함께 구성하는 강력하고도 견고한 플랫폼입니다.</p>
    <p><small class="text-muted">* The havister is a harvester.</small></p>
  </div>
</section>

<!-- Section -->
<section class="box">
  <img class="box-img" src="{% static 'images/people.jpg' %}" alt="People Image">
  <div class="box-pad">
    <h4 class="my-3">플레이어(Player)</h4>
    <p>이용자(Player)는 포인트넛 웹사이트에 로그인하여 하비스터를 운영(Play)할 수 있습니다. 단지 자신의 거래 전략을 하비스터에게 지시하기만 하면 됩니다.</p>
    <p>필요하다면 다른 사람의 전략을 따라 할 수도 있습니다. 하비스터에는 검증된 매매 신호(Signal)들이 준비되어 있으며, 이는 신호 개발자(Creator)들의 오랜 연구 결과입니다.</p>
    <p><small class="text-muted">* The player is a user.</small></p>
  </div>
</section>

<!-- Section -->
<section class="box">
  <img class="box-img" src="{% static 'images/hand.jpg' %}" alt="Hand Image">
  <div class="box-pad">
    <h4 class="my-3">시그널(Signal)</h4>
    <p>매매 신호(Signal)는 하비스터에서 사용되는 자동 거래 서비스입니다. 플레이어 누구나 자신의 포트폴리오에 맞는 신호를 선택하고 따라 할 수 있습니다.</p>
    <p>이 신호(Signal)들은 개발자(Creator)에 의해 개발되고 검증되었으며, 실전 계좌에서 운용됨으로써 그 가치가 입증되었습니다.</p>
    <p><small class="text-muted">* The signal is a trading strategy.</small></p>
  </div>
</section>

<!-- Section -->
<section class="box">
  <img class="box-img" class="mt-3" src="{% static 'images/notes.jpg' %}" alt="Notes Image">
  <div class="box-pad">
    <h4 class="mb-3">크리에이터(Creator)</h4>
    <p>신호 개발자(Creator)는 하비스터 플랫폼의 핵심 자산입니다. 이들은 다양한 매매 신호(Signal)를 개발하며, 이를 이용자(Player)에게 공개합니다.</p>
    <p>이들은 마치 음악을 작곡하듯, 처음 영감을 얻는 것부터 마지막 시연에 이르기까지 헌신적인 노력을 기울여 매매 신호(Signal)를 창조합니다.</p>
    <p><small class="text-muted">* The creator is a signal developer.</small></p>
  </div>
</section>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block meta %}
<!-- SEO -->
<meta name="naver-site-verification" content="9b95a2ec474320b256e11cdb0837c3091c024cc7"/>
<meta name="description" content="포인트넛은 금융상품을 자동 매매하는 로봇 플랫폼을 서비스합니다. 이 플랫폼에는 전략 개발자인 크리에이터와 로봇 이용자인 플레이어가 함께 합니다.">
{% endblock %}

{% block nav-title %}
<span>POINTNUT</span>
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
<!-- Section -->
<section class="box">
  <img class="box-img" src="{% static 'images/havister-1911.jpg' %}" alt="Havister Logo">
  <div class="box-pad">
    <h4 class="my-3">하비스터(Havister)</h4>
    <p>하비스터는 금융 거래를 위한 자동화된 프로그램 매매 시스템입니다. 지금껏 금융사들의 전유물이었던 이 훌륭한 도구를 이제는 개인들도 사용할 수 있게 되었습니다.</p>
    <p>이 시스템은 로봇 소프트웨어(Havister), 플레이어(Player), 매매 전략(Strategy), 크리에이터(Creator)가 함께 구성하는 강력하고도 견고한 플랫폼입니다.</p>
  </div>
</section>

<!-- Section -->
<section class="box">
  <img class="box-img" src="{% static 'images/player-1911.jpg' %}" alt="People Image">
  <div class="box-pad">
    <h4 class="my-3">플레이어(Player)</h4>
    <p>플레이어(Player)는 포인트넛 웹사이트에 로그인하여 하비스터를 플레이(Play)할 수 있습니다. 단지 자신의 매매를 하비스터에게 지시하기만 하면 됩니다.</p>
    <p>필요하다면 다른 사람의 매매를 따라 할 수도 있습니다. 하비스터에는 검증된 매매 전략(Strategy)들이 준비되어 있으며, 이는 크리에이터(Creator)들의 오랜 연구 결과입니다.</p>
  </div>
</section>

<!-- Section -->
<section class="box">
  <img class="box-img" src="{% static 'images/strategy-1911.jpg' %}" alt="Hand Image">
  <div class="box-pad">
    <h4 class="my-3">매매 전략(Strategy)</h4>
    <p>매매 전략(Strategy)은 하비스터 자동화 서비스의 원천 기술입니다. 플레이어(Player) 누구나 자신의 포트폴리오에 맞는 전략을 선택하고 따라 할 수 있습니다.</p>
    <p>이 전략들은 크리에이터(Creator)들에 의해 개발되고 검증되었으며, 실전 계좌에서 운용됨으로써 그 가치가 입증되었습니다.</p>
  </div>
</section>

<!-- Section -->
<section class="box">
  <img class="box-img" src="{% static 'images/creator-1911.jpg' %}" alt="Notes Image">
  <div class="box-pad">
    <h4 class="my-3">크리에이터(Creator)</h4>
    <p>크리에이터(Creator)는 하비스터 플랫폼의 핵심 자산입니다. 이들은 다양한 매매 전략(Strategy)을 개발하며, 이를 플레이어(Player)에게 공개합니다.</p>
    <p>이들은 마치 음악을 작곡하듯, 처음 영감을 얻는 것부터 마지막 시연에 이르기까지 헌신적인 노력을 기울여 매매 전략(Strategy)을 창조합니다.</p>
  </div>
</section>
{% endblock %}

templates/user.html
{% extends "base.html" %}

{% block title %}
<title>{{ user.username|upper }} - Pointnut</title>
{% endblock %}

{% block nav-title %}
<a class="mr-2 green" href="/"><i class="fas fa-chevron-left"></i></a>
<span>{{ user.username|upper }}</span>
{% endblock %}

{% block nav-link %}
<div class="dropdown">
  <button class="btn btn-success btn-xm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-user"></i>
  </button>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item disabled" href="#" tabindex="-1" aria-disabled="true">Profile</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item disabled" href="#" tabindex="-1" aria-disabled="true">Havister</a>
    <a class="dropdown-item disabled" href="#" tabindex="-1" aria-disabled="true">Trades</a>
    <a class="dropdown-item disabled" href="#" tabindex="-1" aria-disabled="true">Returns</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'password_change' %}">Settings</a>
    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
  </div>
</div>
{% endblock %}

{% block header %}
<!-- Alert -->
{% if alert %}
<div class="box mb-2">
  <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
    {{ alert }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
{% endif %}

<!-- Header -->
<header class="box">
  <div class="box-pad d-flex align-items-center">
    <h4 class="my-1 mr-auto">{{ user.first_name }}</h4>
    <p class="mb-0 text-capitalize">
    {% for group in user.groups.all %}
      <span class="badge badge-darkgray font-weight-normal">{{ group.name }}</span>
    {% endfor %}
    </p>
  </div>
</header>
{% endblock %}

{% block main %}
<!-- Section -->
<section class="box">
  <div class="box-pad">
    <h4 class="my-1 text-darkgray">Latest Returns</h4>
  </div>
  <!-- Section Body -->
  {% if closed_trade_list %}
  <div class="box">
    {% for trade in closed_trade_list %}
    <div class="box-pad d-flex align-items-center border-top">
      <div class="d-none d-sm-block w-25 text-center pr-3">
        <p class="h3 font-weight-normal text-gray">{{ forloop.counter }}</p>
      </div>
      <div class="box flex-grow-1">
        <div class="d-flex align-items-center">
          <h5 class="text-kr mr-auto">{{ trade|upper }}</h5>
          <p class="h5 text-{% if trade.change >= 0 %}orange{% else %}cyan{% endif %}">
            <span>{{ trade.change|stringformat:"+0.2f" }}%</span>
          </p>
        </div>
        <div class="d-flex">
          <p class="mb-0 small text-muted mr-auto">
            <span>{{ trade.date_opened|date:'Y.m.d' }}</span>
            <span>~</span>
            <span>{{ trade.date_closed|date:'Y.m.d' }}</span>
          </p>
          <p class="mb-0 small">
            <span class="text-muted">{% if trade.position == 'L' %}LONG{% else %}SHORT{% endif %}</span>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="box-pad">
    <p>거래 기록이 없습니다.</p>
  </div>
  {% endif %}
</section>

<!-- Section -->
<section class="box">
  <div class="box-pad">
    <h4 class="my-1 text-darkgray">Latest Trades</h4>
  </div>
  <!-- Section Body -->
  {% if opened_trade_list %}
  <div class="box">
    {% for trade in opened_trade_list %}
    <div class="box-pad d-flex align-items-center border-top">
      <div class="d-none d-sm-block w-25 text-center pr-3">
        <p class="h3 font-weight-normal text-gray">{{ forloop.counter }}</p>
      </div>
      <div class="box flex-grow-1">
        <div class="d-flex align-items-center">
          <h5 class="text-kr mr-auto">{{ trade|upper }}</h5>
          <p class="h5 text-muted">
            <span></span>
          </p>
        </div>
        <div class="d-flex">
          <p class="mb-0 small text-muted mr-auto">
            <span>{{ trade.date_opened|date:'Y.m.d' }}</span>
            <span>~</span>
            <span></span>
          </p>
          <p class="mb-0 small">
            <span class="text-muted">{% if trade.position == 'L' %}LONG{% else %}SHORT{% endif %}</span>
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="box-pad">
    <p>거래 기록이 없습니다.</p>
  </div>
  {% endif %}
</section>

{% endblock %}

templates/user_base.html
{% extends "base.html" %}

{% block nav-link %}
<div class="dropdown">
  <button class="btn btn-outline-success btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Service
  </button>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{% url 'users:index' %}">Home</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'users:strategy' %}">Strategy</a>
    <a class="dropdown-item" href="{% url 'users:signal' %}">Signal</a>
    <a class="dropdown-item" href="{% url 'users:havister' %}">Havister</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'users:trades_closed' %}">청산 거래</a>
    <a class="dropdown-item" href="{% url 'users:trades_opened' %}">진입 거래</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'password_change' %}">Settings</a>
    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
  </div>
</div>
{% endblock %}